"use client";
import { useEffect, useState } from "react";
import { Shell } from "../../components/Shell";
import { api } from "../../lib/api";

const sampleCsv = "examId,question,type,A,B,C,D,correct,topic\nexam-rla-detailed,What is the main idea?,MCQ,First answer,Correct answer,Third answer,Fourth answer,B,Reading";
export default function Admin() {
  const [exams, setExams] = useState<any[]>([]), [courses, setCourses] = useState<any[]>([]), [message, setMessage] = useState("");
  const [format, setFormat] = useState<"json" | "csv">("csv"), [content, setContent] = useState(sampleCsv), [preview, setPreview] = useState<any>(null);
  const [form, setForm] = useState<any>({ title: "", description: "", courseId: "", subject: "RLA", mode: "PRACTICE", durationSeconds: 2700, passingScore: 60 });
  const load = () => Promise.all([api<any[]>("/admin/exams"), api<any[]>("/admin/courses")]).then(([all, courseRows]) => { setExams(all); setCourses(courseRows); if (!form.courseId && courseRows[0]) setForm((x: any) => ({ ...x, courseId: courseRows[0].id, subject: courseRows[0].subject })); });
  useEffect(() => { load().catch((e: Error) => setMessage(e.message)); }, []);
  async function create() { try { await api("/admin/exams", { method: "POST", body: JSON.stringify({ ...form, durationSeconds: Number(form.durationSeconds), passingScore: Number(form.passingScore) }) }); setMessage("Exam created."); setForm((x: any) => ({ ...x, title: "", description: "" })); load(); } catch (e: any) { setMessage(e.message); } }
  async function checkImport() { try { setPreview(await api("/admin/import/preview", { method: "POST", body: JSON.stringify({ format, content }) })); setMessage(""); } catch (e: any) { setMessage(e.message); setPreview(null); } }
  async function importRows() { try { const result = await api<any>("/admin/import", { method: "POST", body: JSON.stringify({ format, content }) }); setMessage(`Imported ${result.created} question(s).`); setPreview(null); load(); } catch (e: any) { setMessage(e.message); } }
  return <Shell><div className="topbar"><b>Admin CMS</b></div><div className="content"><h1 className="title">Exam authoring</h1><p className="subtitle">Create practice exams, then validate and import question banks.</p>
    <div className="grid grid2" style={{ marginTop: 18 }}><div className="card"><div className="section-title">Create exam</div>{[["Title", "title"], ["Description", "description"], ["Duration (seconds)", "durationSeconds"], ["Passing raw score (%)", "passingScore"]].map(([label, key]) => <label key={key} style={{ display: "block", marginTop: 10 }}><span className="muted">{label}</span><input value={form[key]} onChange={e => setForm({ ...form, [key]: e.target.value })} style={{ display: "block", width: "100%", padding: 10, marginTop: 4 }} /></label>)}<label style={{ display: "block", marginTop: 10 }}><span className="muted">Course</span><select value={form.courseId} onChange={e => { const course = courses.find(c => c.id === e.target.value); setForm({ ...form, courseId: e.target.value, subject: course?.subject ?? form.subject }); }} style={{ display: "block", width: "100%", padding: 10, marginTop: 4 }}>{courses.map(c => <option key={c.id} value={c.id}>{c.title}</option>)}</select></label><label style={{ display: "block", marginTop: 10 }}><span className="muted">Exam mode</span><select value={form.mode} onChange={e => setForm({ ...form, mode: e.target.value })} style={{ display: "block", width: "100%", padding: 10, marginTop: 4 }}><option>PRACTICE</option><option>MOCK</option><option>SKILL</option></select></label><button className="btn btn-primary" onClick={create} style={{ marginTop: 14 }}>Create exam</button></div>
      <div className="card"><div className="section-title">Import question bank</div><p className="muted">CSV columns: examId, question, type, A–D, correct, topic. JSON supports question data and options.</p><div style={{ display: "flex", gap: 8, marginBottom: 10 }}><button className="btn btn-soft" onClick={() => setFormat("csv")}>CSV</button><button className="btn btn-soft" onClick={() => setFormat("json")}>JSON</button></div><textarea value={content} onChange={e => setContent(e.target.value)} rows={13} style={{ width: "100%", padding: 12, border: "1px solid #ddd", borderRadius: 10, fontFamily: "monospace" }} /><div style={{ display: "flex", gap: 8, marginTop: 10 }}><button className="btn btn-soft" onClick={checkImport}>Validate & preview</button><button className="btn btn-primary" disabled={!preview?.valid || preview.valid !== preview.total} onClick={importRows}>Import</button></div>{preview && <div className="toolPanel" style={{ marginTop: 12 }}><b>{preview.valid}/{preview.total} valid rows</b>{preview.errors.map((x: any) => <div key={`${x.row}-${x.message}`}>Row {x.row}: {x.message}</div>)}</div>}</div></div>
    <p className="muted">{message}</p><div className="card" style={{ marginTop: 18 }}><div className="section-title">Existing exams</div>{exams.map(exam => <div key={exam.id} style={{ padding: "12px 0", borderBottom: "1px solid #eee" }}><b>{exam.title}</b><div className="muted">{exam.subject} · {Math.round(exam.durationSeconds / 60)} min · {exam._count.questions} questions · {exam._count.passages} passages</div></div>)}</div>
  </div></Shell>;
}
