"use client";
import {useEffect,useRef,useState} from "react";import {Shell} from "../../../components/Shell";import {api} from "../../../lib/api";
export default function Writing(){
 const ref=useRef<HTMLDivElement>(null);const[time,setTime]=useState(45*60);const[words,setWords]=useState(0);const[prompt]=useState("Analyze which position is better supported by evidence in the source material. Explain how the evidence supports your reasoning.");const[grading,setGrading]=useState<any>(null);
 useEffect(()=>{const id=setInterval(()=>setTime(t=>Math.max(0,t-1)),1000);return()=>clearInterval(id)},[]);
 function update(){const text=ref.current?.innerText||"";setWords(text.trim()?text.trim().split(/\s+/).length:0)}
 async function grade(){const essay=ref.current?.innerText||"";setGrading(await api<any>("/skills/essay/score",{method:"POST",body:JSON.stringify({essay,prompt})}))}
 return <Shell><div className="topbar"><b>RLA Extended Response</b><div style={{display:"flex",gap:10}}><span className="badge">Timer {String(Math.floor(time/60)).padStart(2,"0")}:{String(time%60).padStart(2,"0")}</span><span className="badge">{words} words</span></div></div><div className="content"><h1 className="title">Write your argument</h1><p className="subtitle">{prompt}</p><div className="toolPanel" style={{marginTop:16}}>Spellcheck and browser autocorrect are intentionally disabled in this practice editor to simulate a constrained testing environment.</div><div ref={ref} contentEditable suppressContentEditableWarning spellCheck={false} onInput={update} className="editor" style={{marginTop:16}}/><button className="btn btn-primary" onClick={grade} style={{marginTop:12}}>AI practice scoring</button>{grading&&<div className="card" style={{marginTop:18}}><div className="section-title">Practice score: {grading.score}/6</div>{grading.traits?.map((t:any)=><div key={t.id} style={{padding:"12px 0",borderBottom:"1px solid #eee"}}><b>{t.name}: {t.score}/{t.max}</b><div className="muted">{t.feedback}</div></div>)}{grading.summary&&<p className="muted">{grading.summary}</p>}</div>}</div></Shell>
}
