"use client";
import { useRef, useState } from "react";
import { Shell } from "../../../components/Shell";
import { api } from "../../../lib/api";

export default function Speaking() {
  const [rec, setRec] = useState(false), [seconds, setSeconds] = useState(0), [data, setData] = useState<Blob | null>(null), [result, setResult] = useState<any>(null), [message, setMessage] = useState("");
  const media = useRef<MediaRecorder | null>(null), timer = useRef<any>(null);
  async function start() { try { const stream = await navigator.mediaDevices.getUserMedia({ audio: true }); const recorder = new MediaRecorder(stream); const chunks: Blob[] = []; recorder.ondataavailable = e => chunks.push(e.data); recorder.onstop = () => { setData(new Blob(chunks, { type: recorder.mimeType || "audio/webm" })); stream.getTracks().forEach(t => t.stop()); }; media.current = recorder; recorder.start(); setRec(true); setSeconds(0); timer.current = setInterval(() => setSeconds(s => s + 1), 1000); } catch { setMessage("Microphone permission is required."); } }
  function stop() { media.current?.stop(); setRec(false); clearInterval(timer.current); }
  async function analyze() { if (!data) return; setMessage("Transcribing with Azure Speech…"); try { const body = new FormData(); body.append("audio", data, "speaking.webm"); body.append("locale", "en-US"); setResult(await api<any>("/skills/speaking/analyze", { method: "POST", body })); setMessage(""); } catch (e: any) { setMessage(e.message); } }
  const rating = result?.confidence == null ? "—" : result.confidence >= 85 ? "Excellent" : result.confidence >= 65 ? "Good" : "Needs practice";
  return <Shell><div className="topbar"><b>Speaking Lab</b></div><div className="content"><h1 className="title">Speaking practice</h1><p className="subtitle">Record an answer, then use Azure Speech for a transcript and fluency indicators.</p><div className="card" style={{ marginTop: 18 }}><h2>Prompt</h2><p>Should communities invest more in public learning spaces? Give a clear position and support it with reasons and examples.</p><div style={{ display: "flex", gap: 10, alignItems: "center" }}>{!rec ? <button className="btn btn-primary" onClick={start}>Start recording</button> : <button className="btn btn-danger" onClick={stop}>Stop</button>}{rec && <span><span className="recordDot" /> Recording {seconds}s</span>}</div>{data && <><audio controls src={URL.createObjectURL(data)} style={{ width: "100%", marginTop: 14 }} /><button className="btn btn-primary" onClick={analyze} style={{ marginTop: 10 }}>Analyze with Azure Speech</button></>}</div>{message && <p className="muted">{message}</p>}
    <div className="grid grid3" style={{ marginTop: 18 }}><div className="card"><b>Words per minute</b><div className="kpi">{result?.wordsPerMinute ?? "—"}</div><div className="muted">From Azure transcript</div></div><div className="card"><b>Long pauses</b><div className="kpi">{result?.longPauses ?? "—"}</div><div className="muted">Pauses of at least one second</div></div><div className="card"><b>Recognition confidence</b><div className="kpi">{result?.confidence == null ? "—" : `${result.confidence}%`}</div><div className="muted">{rating}</div></div></div>{result && <div className="card" style={{ marginTop: 18 }}><div className="section-title">Transcript</div><p className="passageText">{result.transcript || "No speech was recognized."}</p><p className="muted">{result.pronunciation.status}</p></div>}</div></Shell>;
}
