"use client";
import {useRef,useState} from "react";import {Shell} from "../../../components/Shell";
export default function Speaking(){
 const [rec,setRec]=useState(false);const [seconds,setSeconds]=useState(0);const [data,setData]=useState<Blob|null>(null);const media=useRef<MediaRecorder|null>(null);const timer=useRef<any>(null);
 async function start(){const stream=await navigator.mediaDevices.getUserMedia({audio:true});const r=new MediaRecorder(stream);const chunks:Blob[]=[];r.ondataavailable=e=>chunks.push(e.data);r.onstop=()=>{setData(new Blob(chunks,{type:"audio/webm"}));stream.getTracks().forEach(t=>t.stop())};media.current=r;r.start();setRec(true);setSeconds(0);timer.current=setInterval(()=>setSeconds(s=>s+1),1000)}
 function stop(){media.current?.stop();setRec(false);clearInterval(timer.current)}
 const wpm=Math.round((seconds?Math.max(1,Math.floor(seconds/60))*120:0));
 return <Shell><div className="topbar"><b>Speaking Lab</b></div><div className="content"><h1 className="title">Speaking practice</h1><p className="subtitle">Prepare for 60–90 seconds, then speak for up to 2 minutes.</p><div className="card" style={{marginTop:18}}><h2>Prompt</h2><p>Should communities invest more in public learning spaces? Give a clear position and support it with reasons and examples.</p><div style={{display:"flex",gap:10,alignItems:"center"}}>{!rec?<button className="btn btn-primary" onClick={start}>🎙 Start recording</button>:<button className="btn btn-danger" onClick={stop}>⏹ Stop</button>}{rec&&<span><span className="recordDot"/> Recording {seconds}s</span>}</div>{data&&<audio controls src={URL.createObjectURL(data)} style={{width:"100%",marginTop:14}}/>}</div><div className="grid grid3" style={{marginTop:18}}><div className="card"><b>Words per minute</b><div className="kpi">{wpm}</div><div className="muted">Local approximation from session time</div></div><div className="card"><b>Pauses</b><div className="kpi">—</div><div className="muted">Add server speech analysis for production</div></div><div className="card"><b>Pronunciation</b><div className="kpi">—</div><div className="muted">Ready for STT/assessment provider integration</div></div></div></div></Shell>
}
